### PR TITLE
Ch grunt to gulp 150397535

### PR DESCRIPTION
**Pull request by louisdante9**

### CODE REVIEW

**Review by THEozmic — APPROVED** [review]
GTM

**Review by THEozmic — CHANGES_REQUESTED** [review]
Use es6

**Review by QUDUSKUNLE — APPROVED** [review]
GTM

**Review by THEozmic — APPROVED** [review]

**Review by mradeybee — CHANGES_REQUESTED** [review]
@louisdante9 lets talk about this PR as soon as you get into the office today.

**Pull request merged**
