### PR TITLE
Ch update dependencies b 150511114

### PR DESCRIPTION
**Pull request by QUDUSKUNLE**
# What does this PR do?
All dependencies are updated. Needed to be merged to Staging for others to pull and work from there.

### CODE REVIEW

**Review by mradeybee — CHANGES_REQUESTED** [review]
I can still see the bower components folder. Please make sure its removed. Also, why did you change `https` to `http` in so many places?

**Comment by QUDUSKUNLE** [comment]
Sorry! http to https.

When I deployed, I was getting blank page and I called the attention of
other members. It was @johadi that said Heroku does not support http any
longer. So, we agreed to change to https and see what will happen. I did
and it solved the problem.

**Comment by mradeybee** [comment]
@QUDUSKUNLE now you are switching back to http?

**Comment by QUDUSKUNLE** [comment]
No, I'm stilling using https.

**Comment by QUDUSKUNLE** [comment]
No, I'm still using https.

**Review by mradeybee — APPROVED** [review]
GTM

**Pull request merged**
